
services:
  nginx:
    image: nginx:1.26.0
    container_name: nginx_server
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/html
    networks:
      - frontend
      - backend

  php:
    image: php:7.4-fpm
    container_name: backend_PHP
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: backend_mySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: backend_PHPadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend

volumes:
  mysql-data:

networks:
  frontend:
  backend:
